{% set name = "suds" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/suds-{{ version }}.tar.gz
  sha256: 1d5cfa74117193b244a4233f246c483d9f41198b448c5f14a8bad11c4f649f2b

build:
  noarch: python
  # Default package name is suds-community and needs to be overridden with an environment variable
  # https://github.com/suds-community/suds/blob/a616d96b070ca119a532ff395d4a2a2ba42b257c/setup.py#L648
  # This will change in in the 2.0.0 release
  # https://github.com/suds-community/suds/blob/a616d96b070ca119a532ff395d4a2a2ba42b257c/README.md#overview
  script: SUDS_PACKAGE=suds {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - suds
    - suds.bindings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/suds-community/suds
  summary: Lightweight SOAP client (community fork)
  license: LGPL-3.0-only
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
